include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
    missing_return: error
    must_be_immutable: error

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - prefer_single_quotes
