spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/redbank_dev
    username: redbank_user
    password: redbank_password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    
redbank:
  firebase:
    service-account-path: classpath:firebase-dev.json
  cloudinary:
    url: ${CLOUDINARY_URL:cloudinary://123:abc@test}
