spring:
  application:
    name: redbank-backend
  profiles:
    active: dev
  jackson:
    property-naming-strategy: SNAKE_CASE

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

server:
  port: ${PORT:8080}
