// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK5q-cC-rFCYJ4it59TRbMG0YBknCJkgQ',
    appId: '1:50759587733:web:cfd5f7a35faa124b03489c',
    messagingSenderId: '50759587733',
    projectId: 'red-bank-65c43',
    authDomain: 'red-bank-65c43.firebaseapp.com',
    storageBucket: 'red-bank-65c43.firebasestorage.app',
    measurementId: 'G-VRE5TYPXW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2sv-hOV6NeON31irL6hu0dMFu9V5iq6g',
    appId: '1:50759587733:android:9bf4abf20b2b1ef003489c',
    messagingSenderId: '50759587733',
    projectId: 'red-bank-65c43',
    storageBucket: 'red-bank-65c43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFJvjRpGIktcWTn6mr1qVY2spHs2FKwH0',
    appId: '1:50759587733:ios:05a21d35f071a7fb03489c',
    messagingSenderId: '50759587733',
    projectId: 'red-bank-65c43',
    storageBucket: 'red-bank-65c43.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
